# baseURL = 'https://looks.wtf/'
baseURL = 'https://looks-wtf.pages.dev/'
languageCode = 'en-us'
relativeURLs = true
disableKinds = [
    "taxonomy",
    "taxonomyTerm",
]
uglyURLs = true

[outputs]
page = ["html", "json"]

[outputFormats.html]
noUgly = true

[outputFormats.json]
mediatype = "application/json"
path = "api/v1"
noUgly = false
